production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=hva-fys --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master

stages: 
  - build
  - deploy

build:
  stage: build
  script:
    - cd packages/client
    - npm install
    - npm run build
  only:
  - master

deploy:
  stage: deploy
   script:
    - cd packages/client
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  only:
  - master