stages: 
  - build
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: none
  before_script:
    - git clone git@gitlab.fdmci.hva.nl:ID1S1-fys/fasten-your-seat-belts.git
  script:
    - cd packages/client
    - npm install
    - npm run build
  only:
  - master

deploy:
  stage: deploy
  script:
    - cd packages/client
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  only:
  - master